name: CI

on:
  push:
    branches: [mention-non-collaborators]
  pull_request_target:
    branches: ['**']

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - run: |
        git fetch origin $REF
        git checkout $REF
        git checkout -b mention-non-collaborators-dist
      env:
        REF: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run linter and tests
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Push updated dist
      run: |
        npm run build
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git -c user.name="github-actions[bot]" \
            -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "Automatically generated dist files"
          git push --force origin mention-non-collaborators-dist
          echo "Please update the branch with automatically generated dist files"
          exit 1
        fi
